version: "3"
services:
  api:
    image: biadiritie/fastapi
    depends_on:
      - postgres
    ports:
      - 80:8000
    volumes:
      - ./:/usr/src/app:ro
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    #env_file:
    #  - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
